export const projects = [
  {name:'Grimbyte Technologies', description:'Consulting firm specialising in marketing transformation & GTM strategies', role:'Brand Strategy Intern', duration:'4 weeks', color:'blue', points:['Configured GA4, Meta & SEMrush dashboards for 6+ clients, replacing vanity metrics with performance KPIs.','Mapped customer journeys for 4 clients to identify friction points, reduce drop-off, and improve lead capture.'], stats:[['6+','Clients'],['4','CX journeys mapped'],['3','Tools deployed']]},
  {name:'Blue Tea', description:"India’s leading herbal tea brand, featured on Shark Tank India, with 1M+ global customers", role:'Live Project Associate', duration:'4 weeks', color:'cream', points:['Secured 5+ strategic B2B partnerships to distribute 2,000+ units through a targeted offline activation.','Built an influencer campaign model with 90+ creators, achieving ₹0.10 CPV and outperforming industry benchmarks.'], stats:[['90+','Creators outreached'],['₹0.10','CPV achieved'],['2K+','Units distributed']]},
  {name:'Dr. Water', description:'Global US-based brand delivering premium hydrogen hydration solutions', role:'Project Head', duration:'8 weeks', color:'dark', points:['Identified 6 key customer personas through primary and secondary research, analysing 200+ responses.','Benchmarked 18+ hydration brands and synthesised over 2,000 data points to inform targeted marketing strategies.'], stats:[['6','Personas mapped'],['2K+','Data points'],['18+','Brands benchmarked']]},
  {name:'Frost & Sullivan', description:'International consulting firm specialising in market research & strategic advisory', role:'Live Project Associate', duration:'4 weeks', color:'blue', points:['Benchmarked six mobility domains, identifying synergies projected to unlock ₹42,000 crore+ in market opportunities.','Ranked 200+ technologies using the Mobility Innovation Scoring Model to identify the top 10 strategic innovations.'], stats:[['200+','Tech ranked'],['₹42K Cr+','Market opportunity'],['6','Mobility domains']]},
];
export const stations = [
 {station:'Vishwavidyalaya',name:'Krishna Shukla',type:'Growth',subtitle:'Engineered creator growth systems capturing massive reach & brand revenue.',points:['Created relatable POV content to acquire cold audiences.','Turned passive viewers into active distributors with a 3× loop rate.','Operationalised and scaled a 40+ show touring business.'],stats:[['186M+','Reach'],['₹4.4L','Revenue'],['32×','ROI']],art:'1.stillrollin’.png'},
 {station:'GTB Nagar',name:'Rntl.',type:'Acquisition',subtitle:'Validated acquisition channels for Gen Z sustainable fashion rentals.',points:['Used borrowed equity to remove the consumer trust deficit.','Positioned the brand as a legitimate player from day one.','Made credible industry voices endorse renting as a lifestyle.'],stats:[['500+','Beta users'],['4×','Growth'],['Gen Z','Audience']],art:'rntl..png'},
 {station:'Kashmere Gate',name:'Sinkari',type:'Retention',subtitle:'Architected automated email flows to dramatically lift retention.',points:['Built automated email funnel architecture from scratch.','Plugged revenue bleeding from daily abandoned carts.','Recovered 25+ carts and boosted conversion by 10%.'],stats:[['10%','Revenue lift'],['90%','Retention'],['30D','Window']],art:'1.mschficarousel.png'},
 {station:'Rajiv Chowk',name:'Dramsoc',type:'Scale',subtitle:'Secured brand sponsorships and scaled digital presence for a flagship fest.',points:['Closed ₹55L+ in brand sponsorships with 30+ brands.','Grew Instagram to 10K+ followers as DU’s #1 club.','Generated 33M+ total campaign reach for flagship events.'],stats:[['₹55L+','Sponsorship'],['40K','Footfall'],['72H','Duration']],art:'5.histrionicajudges.png'},
 {station:'Mandi House',name:'Jio Hotstar',type:'Launch',subtitle:'Orchestrated a campus launch generating massive organic reach.',points:['Turned a streaming show launch into an organic campus moment.','Scaled 25–40 micro-influencers to reach 30,000+ students.','Converted event footfall into 8,000+ peer-to-peer shares.'],stats:[['7L+','Impressions'],['15%','Conversion'],['40K+','Signups']],art:'2.beyondthehypei3-tiler.png'},
];
export const artworks = [
 ['1.charades.png','Charades — event poster'],['2.beyondthehypei3-tiler.png','Beyond the hype — campaign design'],['5.histrionicajudges.png','Histrionica — festival creative'],['1.mschficarousel.png','MSCHF — social creative'],['2.playstationicrossroads.png','PlayStation × Crossroads'],['3.zomatoiassignmentpost.png','Zomato — brand concept'],['7.1.dusummervacation.png','DU summer vacation'],['4.sharktankpanelibizstreet.png','Shark Tank — panel creative'],['1.1.prajaktakoliibooklaunch(1).png','Prajakta Koli — book launch'],['1.stillrollin’.png','Still rollin’'],['2.raahwarga.png','Raah Warga — music artwork'],['rntl..png','Rntl. — visual identity'],
];
